server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm?currentSchema=public
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

stats:
  service-id: stats-server