server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/stats/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**,/categories/**,/compilations/**,/admin/events/**,/admin/categories/**,/admin/compilations/**,/users/*/events/**