spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/stats/**,/stats
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**,/admin/users
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/requests
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**,/events,/categories/**,/categories,/compilations/**,/compilations,/admin/events/**,/admin/events,/admin/categories/**,/admin/categories,/admin/compilations/**,/admin/compilations,/users/*/events/**,/users/*/events